DEBUG = True

POSTGRES_USER = 'postgres'
POSTGRES_PASSWORD = 'docker'
POSTGRES_HOST = '192.168.99.100'
POSTGRES_PORT = '5432'
POSTGRES_DB = 'flask-api'

SQLALCHEMY_DATABASE_URI = f'postgresql+psycopg2://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}'

SQLALCHEMY_TRACK_MODIFICATIONS = True