"""empty message

Revision ID: 54892bfc5a38
Revises: 01286753ad11
Create Date: 2020-11-14 19:50:35.691017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54892bfc5a38'
down_revision = '01286753ad11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projeto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('projetoa')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projetoa',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='projetoa_pkey')
    )
    op.drop_table('projeto')
    # ### end Alembic commands ###
